README.md
client/k8s/decoder.go
examples/example-cert.yaml
glide.lock
glide.yaml
service/create/cert_signer.go
service/create/pki.go
service/create/pki_test.go
service/create/service.go
service/create/third_party_resource.go
vendor/github.com/giantswarm/certificatetpr/.gitignore
vendor/github.com/giantswarm/certificatetpr/LICENSE
vendor/github.com/giantswarm/certificatetpr/README.md
vendor/github.com/giantswarm/certificatetpr/custom_object.go
vendor/github.com/giantswarm/certificatetpr/glide.lock
vendor/github.com/giantswarm/certificatetpr/glide.yaml
vendor/github.com/giantswarm/certificatetpr/list.go
vendor/github.com/giantswarm/certificatetpr/name.go
vendor/github.com/giantswarm/certificatetpr/spec.go

Towards giantswarm/giantswarm#1255 and #13 
This PR integrates the certificatetpr, creates the TPR on boot and watches for cert TPOs. The AddFunc is implemented and will issue a cert. The error handling for issuing certs has been cleaned up as requested in #13
Still to be implemented
- DeleteFunc
- UpdateFunc
- Saving certs as k8s secrets
- Retry logic on failure
I'd like to do these as follow on PRs.
~~I'm also still tracking down a bug with bare domains not being accepted as alternate names for the certs.~~

Integrate certificatetpr into operator

---

examples/example-cert.yaml
glide.lock
service/create/cert_signer.go
service/create/k8s_secret.go
service/create/service.go
vendor/github.com/giantswarm/certificatetpr/spec.go

Towards giantswarm/giantswarm#1255
This PR implements saving the certs issued by Vault as a k8s secret. It also implements the delete watch which deletes the secret when the TPO is deleted.
Not yet implemented is updateFunc as well as retry logic for Vault and K8s API calls. These will be done as follow up PRs.

Save certificates as k8s secrets and implement delete watch

---

service/ca/error.go
service/ca/pki.go
service/ca/pki_test.go
service/ca/service.go
service/crt/cert_signer.go
service/crt/error.go
service/crt/k8s_secret.go
service/crt/service.go
service/crt/third_party_resource.go
service/service.go

Toward giantswarm/giantswarm#1255 and implements #11 
This PR splits the Create service into Ca and Crt services. This is to prepare for moving the CA setup logic to a separate ca-operator with it's own TPR. Also fixes some incorrect comments.

Split Create service into Ca and Crt services

---

circle.yml

`1.8.0` is the default version now

Removes extraneous golang version from build

---

examples/api-cert.yaml
examples/apiserver-cert.yaml
examples/calico-cert.yaml
examples/etcd-cert.yaml
examples/worker-cert.yaml

Towards giantswarm/giantswarm#1255 
This PR adds example certs for each cluster component. The actual certificate TPOs will be created by kubernetesd using data from the cluster TPO but there are some gaps currently.
- apiserver
- worker
- etcd
- calico
I'd like to get these TPOs as close to the actual ones as possible. I'll then automate in kubernetesd. For now I've agreed with @asymmetric that we'll use the default namespace. This is while we decide if the TPOs should live in the cluster namespace.

Add example certs for all cluster components.

---

kubernetes/deployment.yaml

The vault ca is in `/etc/ssl/certs/`, so we need to mount that into cert-operator

Add mounts for /etc/ssl/certs/

---

service/crt/service.go

Towards giantswarm/giantswarm#1371
Update watch for certificates is not yet implemented. Removing the current logging as its generating a lot of logs and not really helping.

Remove UpdateFunc logging

---

service/ca/pki.go
service/crt/cert_signer.go
service/crt/k8s_secret.go
service/crt/service.go

Towards giantswarm/giantswarm#1371
This PR improves the type handling and may help reduce the high memory usage on AWS.
- The watches now cast to a pointer to the custom object rather than the value.
- Everywhere else a certificatetpr.Spec value is passed and this simplifies the code in several places.

Better type handling

---

kubernetes/deployment.yaml

Towards giantswarm/giantswarm#1388
Fixes problem with operator failing to start because values can't be read from the config map. This is because the config args are being parsed as strings rather than string slices. Meaning that the secrets file is read but not the config map.
The fix is to specify the config files and dirs examples multiple times as shown in this pflag [issue](https://github.com/spf13/pflag/issues/40). The bug is strange because it occurs in k8s but not locally.

Use multiple args for config file flags

---

examples/api-cert.yaml
examples/calico-cert.yaml
examples/etcd-cert.yaml
examples/service-account-cert.yaml
examples/worker-cert.yaml

This PR adds a missing example cert for the service account. It also does some boyscouting to make it possible launch a "local" AWS cluster using them.
Changes are
- clusterID is `example-cluster` to match AWS example TPO.
- simpler domain format `api.example-cluster.aws.giantswarm.io`  but uses `aws.giantswarm.io` which is delegated to Route 53 from CloudFlare.

add service-account  and improve example TPOs

---

README.md
examples/api-cert.yaml
examples/calico-cert.yaml
examples/etcd-cert.yaml
examples/service-account-cert.yaml
examples/vault.yaml
examples/worker-cert.yaml

Fixes #40 
Adds docs for running the operator locally. Also helps with running aws-operator locally as the example cert TPOs match the example cluster TPO.

Docs for running cert-operator locally

---

service/crt/service.go

See the Traefik issue and PR linked in #32
This is an attempt to fix why delete watches aren't being triggered. Sets resync period to 5 minutes. Currently this is set to 0 so it delays the resync for as long as possible.
If this fix works we need to implement in operatorkit. As this problem also happens with `aws-operator` and means we need to clean up AWS resources manually.

Set resync period to 5 minutes to fix problem with delete watch

---

service/crt/service.go

This change seems to have introduced another problem: the time it takes for the operator to create secrets has increased.

Revert resend period change it didn’t fix issue and made logs noisy

---

service/ca/pki.go
service/crt/cert_signer.go
service/crt/k8s_secret.go
service/crt/service.go

Fixes #10 
This is some boyscouting I did a while back I want to finish off. It adds retry support to the methods called in the addFunc and deleteFunc.

Adds retry support to methods called by the operator

---

kubernetes/configmap.yaml
kubernetes/deployment.yaml

This partially reverts https://github.com/giantswarm/cert-operator/pull/64.

reverted secret changes in kubernetes directory

---

flag/service/vault/config/certificate/certificate.go
flag/service/vault/config/config.go
helm/cert-operator-chart/templates/configmap.yaml
kubernetes/configmap.yaml
main.go
service/crt/cert_signer.go

This fix adds the allowed domains when issuing certs so the vault role is correct.

Set allowed domains when issuing certs

---

examples/local/env.sh
examples/local/setup-minikube.sh
examples/local/teardown.sh

The setup script is specific for minikube, maybe this could be configured.

add scripts to automate the setup and teardown of the local example

---

examples/local/api-cert.tmpl.yaml

This will prevent errors in guest cluster's ingress controller:
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                        READY     STATUS             RESTARTS   AGE
kube-system   calico-node-fbtps                           2/2       Running            0          11m
kube-system   calico-node-nd13n                           2/2       Running            4          11m
kube-system   calico-node-v256n                           2/2       Running            5          11m
kube-system   calico-policy-controller-1843598625-th5nw   1/1       Running            4          11m
kube-system   default-http-backend-2945164050-kxfxr       1/1       Running            0          11m
kube-system   default-http-backend-2945164050-p46k7       1/1       Running …
```

set ipSans for the api cert in local example

---

examples/cert-resource-lab-chart/templates/worker-cert.yaml

Fixes a bug with the local setup. Flag needs to be true because kubernetes and k8s-master-vm are alt names for the cert.

Set allow bare domains to true for worker cert

---

service/version_bundles.go

Otherwise we will not be able to make a non wip release bundle.

Change wip to false

---

integration/operator_test.go

This is a quick fix for the test that doesn't use apiextensions, I'm working on a separate branch for putting them in place.

update to CRD changes

---

.circleci/config.yml

Uses localkube (minikube with `--vm-driver=none`) from e2e-harness. This way minikube is run on circleCI machines and we don't need to spin up an AWS instance for each e2e execution. Also the setup is slightly quicker.

e2e: use localkube

---

service/certconfig/framework.go

We come closer to situations in which the oldest guest clusters run on expired certificates. Back then we created cert configs that do not obtain any version bundle version. This PR makes the certificates at least to be renewed so in case we get into another situation like this we have one reason less to worry.

reconcile empty version bundle version to support legacy secrets

---

Gopkg.lock
vendor/github.com/giantswarm/vaultrole/current.go
vendor/github.com/giantswarm/vaultrole/error.go

New Vault release (at least for us 0.9.3) brought changes in its API for
certificate AltName formatting. New vaultrole dependency has fixes for
this.

Update vaultrole dependency

---

Gopkg.lock
vendor/github.com/giantswarm/certs/searcher.go

This fixes issue with old clusters that don't have calico-etcd-client
certs.

Update certs dependency

---

helm/cert-operator-chart/templates/rbac.yaml

Last time I've added `get` only. Now also adding `list`.
See: https://github.com/giantswarm/cert-operator/pull/177

Add listing pods to RBAC role

---

helm/cert-operator-chart/templates/configmap.yaml

24h is too low as we need to roll out and communication to a customer can take some extra time.
There isn't any harm in regenerating sooner.

increase-expiration-threshold

---

helm/cert-operator-chart/templates/configmap.yaml
helm/cert-operator-chart/templates/deployment.yaml
helm/cert-operator-chart/templates/pull-secret.yml
helm/cert-operator-chart/templates/rbac.yaml
helm/cert-operator-chart/templates/secret.yml
helm/cert-operator-chart/templates/service-account.yaml
helm/cert-operator-chart/templates/service.yaml
helm/cert-operator-chart/values.yaml

in order to be able change namespace where operator is installed we need to template the namespace in the manifest, this is for kvm e2e

move-namespace-to-values

---

Gopkg.lock
helm/cert-operator-chart/templates/configmap.yaml
vendor/github.com/giantswarm/microkit/command/daemon/command.go
vendor/github.com/giantswarm/microkit/command/daemon/flag/server/enable/debug/debug.go
vendor/github.com/giantswarm/microkit/command/daemon/flag/server/enable/enable.go
vendor/github.com/giantswarm/microkit/command/daemon/flag/server/server.go
vendor/github.com/giantswarm/microkit/server/server.go

Added debug server exposes net/http/pprof interface in
http://127.0.0.1:6060/debug.
This helps with profiling running service e.g. when it's OOMing.
Towards https://github.com/giantswarm/giantswarm/issues/4088

Update microkit dep & enable debug server

---

flag/service/crd/crd.go
flag/service/service.go
helm/cert-operator-chart/templates/configmap.yaml
helm/cert-operator-chart/values.yaml
main.go
service/controller/cert.go
service/service.go

On KVM e2e tests there are multiple instances of operators running at
the same time. In order to prevent race conditions, add label selector
to informer to only process CRs meant for current instance of operator.
Towards https://github.com/giantswarm/giantswarm/issues/4196#issuecomment-421297710

Add CRD label selector for e2e tests

---

service/collector/vault.go

Following review command: https://github.com/giantswarm/chart-operator/pull/262#discussion_r303768629
Several `'%#v` usage changing into `%#q`.

Logging fmt

---

Gopkg.lock
main.go
pkg/project/project.go
service/service.go
vendor/github.com/giantswarm/microendpoint/LICENSE
vendor/github.com/giantswarm/microendpoint/endpoint/version/endpoint.go
vendor/github.com/giantswarm/microendpoint/endpoint/version/response.go
vendor/github.com/giantswarm/microendpoint/service/version/request.go
vendor/github.com/giantswarm/microendpoint/service/version/response.go
vendor/github.com/giantswarm/microendpoint/service/version/service.go
vendor/github.com/giantswarm/microkit/command/command.go
vendor/github.com/giantswarm/microkit/command/version/command.go

This PR exposes the version of cert-operator via version command and version endpoint.
Also moves project information under pkg/project.

Exposes version

---

service/controller/v2/key/key.go
service/controller/v2/key/key_test.go
service/controller/v2/resources/vaultcrt/current.go

Toward https://github.com/giantswarm/giantswarm/issues/6442
We will skip checking running pods on cluster namespace if only that `CertConfig` is not supporting any more.
In this particular PR, we are aiming for deletion of `calico` cert.

Skip checking running pods when deleting non-supporting certconfigs.

---

service/collector/vault.go
service/controller/cert.go
service/controller/v2/resource_set.go
service/controller/v2/resources/vaultaccess/create.go
service/controller/v2/resources/vaultaccess/delete.go
service/controller/v2/resources/vaultaccess/error.go
service/controller/v2/resources/vaultaccess/resource.go

When we update Vault on the control planes the operator throws a couple of errors which we should simply handle a bit more graceful. 
> {"caller":"github.com/giantswarm/cert-operator/vendor/github.com/giantswarm/operatorkit/resource/wrapper/retryresource/crud_resource_ops_wrapper.go:71","controller":"cert-operator","event":"update","function":"GetCurrentState","level":"warning","loop":"91395","message":"retrying due to error","object":"/apis/core.giantswarm.io/v1alpha1/namespaces/default/certconfigs/sh0z0-app-operator-api","resource":"vaultpkiv2","stack":"[{/go/src/github.com/giantswarm/cert-operator/vendor/github.com/giantswarm/operatorkit/resource/wrapper/retryresource/crud_resource_ops_wrapper.go:64: } {/go/src/github.com/giantswarm/cert-operator/service/controller/v2/resources/vaultpki …

handle vault updates more graceful internally

---

service/controller/cert.go
service/controller/v2/resource_set.go
service/controller/v2/resources/cleaning/create.go
service/controller/v2/resources/cleaning/delete.go
service/controller/v2/resources/cleaning/error.go
service/controller/v2/resources/cleaning/resource.go

Toward https://github.com/giantswarm/giantswarm/issues/7488
Deleting all remaining `certConfigs` by checking whether cluster namespace is deleted or not.

Cleaning certconfig belongs to deleted TCs

---

helm/cert-operator-chart/values.yaml

Via https://github.com/giantswarm/cert-operator/pull/231 image registry domain was made configurable, but no default value was set, and this broke e2e tests deploying cert-operator, like azure-operator I was testing https://github.com/giantswarm/azure-operator/pull/603
This PR configures `quay.io` as default image registry domain.

Configure default image registry domain

---

helm/cert-operator-chart/templates/secret.yml

Following https://github.com/giantswarm/opsctl/pull/552
As we still want to make it possible updating tokens with a single command, this change allows embedding just token instead of a whole yaml config from installation
Merging after updating installations repo

Template config struct into secret

---

go.mod
pkg/label/label.go
service/controller/key/key.go
service/controller/key/spec.go
service/controller/resource_set.go
service/controller/resources/vaultcrt/current.go
service/controller/resources/vaultcrt/desired.go
service/controller/resources/vaultcrt/desired_test.go
service/controller/resources/vaultcrt/metric.go

Towards: https://github.com/giantswarm/giantswarm/issues/9343
This reverts PR https://github.com/giantswarm/cert-operator/pull/272
We can't switch to watching with labels because we still have lot of
CertConfig CR which do not have this label and we need to reconcile
those.

Revert "watch CR with cert-operator.giantswarm.io/version label (#272)"

---

pkg/project/project.go

Towards: https://github.com/giantswarm/giantswarm/issues/10389
Set version to `0.1.0` which is the current version of cert-operator.

release 0.1.0

---

CHANGELOG.md
CODEOWNERS
MAINTAINERS
pkg/project/project.go

Some changelog entries were untrue. This will be tagged as `0.1.0.1` which reconciles `0.1.0` still. This is necessary to include the `CRD` changed (mainly no longer ensuring the CRD) with version `0.1.0`.

Prepare retag of 0.1.0

---

CHANGELOG.md
pkg/project/project.go

Towards https://github.com/giantswarm/giantswarm/issues/12653
Version like `0.1.0-1`, which are expected to replace e.g. `0.1.0`, should not be set in `project.go`

Bring back version 0.1.0

---

helm/cert-operator/templates/rbac.yaml

This somehow became necessary between starting the 1.0.0 release PR and the release itself, possibly related to management cluster version upgrade or https://github.com/giantswarm/cert-operator/pull/330.

Add list for clusters

---

CHANGELOG.md
service/controller/resources/vaultaccess/create.go

Towards: https://github.com/giantswarm/roadmap/issues/660 and https://github.com/giantswarm/roadmap/issues/657
This PR makes cert-operator renew its vault token at every reconciliation loop to prevent it from expiring

Renew token

---

CHANGELOG.md
helm/cert-operator/values.yaml

Towards
- https://github.com/giantswarm/roadmap/issues/3017
This PR replaces any occurrence of `docker.io` in `values.yaml` files with `gsoci.azurecr.io`,
to make the new ACR registry the default one.

Configure gsoci.azurecr.io as the registry to use by default

---

CHANGELOG.md
service/controller/cert.go

Towards: https://github.com/giantswarm/giantswarm/issues/30400
With this PR, any errors in the cleanup phase of unused PKIs won't prevent the operator from running but just warn

Avoid exiting with a failure at startup time if the PKI cleanup fails.
