giantswarm/cert-operator

- kubernetes/deployment.yaml
Use a single replica for the operator since we don't have leadership election.
> Use a single replica for the operator

- kubernetes/deployment.yaml
Towards https://github.com/giantswarm/giantswarm/issues/1105
> Adds initial requests and limits

- kubernetes/deployment.yaml
Towards https://github.com/giantswarm/giantswarm/issues/1087
> Moves image and pull secret to quay

- README.md
Towards https://github.com/giantswarm/giantswarm/issues/1087
> Adds quay.io badge

- helm/cert-operator-chart/Chart.yaml
- helm/cert-operator-chart/templates/configmap.yaml
- helm/cert-operator-chart/templates/deployment.yaml
Towards https://github.com/giantswarm/giantswarm/issues/1561
> Adds helm chart

- helm/cert-operator-chart/Chart.yaml
- helm/cert-operator-chart/templates/deployment.yaml
Towards https://github.com/giantswarm/architect/pull/128
> Updates sha template

- README.md
- helm/cert-operator-chart/templates/configmap.yaml
- helm/cert-operator-chart/templates/deployment.yaml
- helm/cert-operator-chart/templates/pull-secret.yml
- helm/cert-operator-chart/templates/secret.yml
- kubernetes/configmap.yaml
- kubernetes/deployment.yaml
Towards https://github.com/giantswarm/giantswarm/issues/1603.
> added secret templates

- examples/local/README.md
Slight improvement to the snippet, matches the one in aws-operator now.
> Improve readme to match aws-operator

- service/service.go
See https://github.com/giantswarm/kvm-operator/pull/243.
> retry framework forever

- service/key/key.go
- service/resource/vaultcrt/current.go
- service/resource/vaultcrt/desired.go
- service/resource/vaultcrt/desired_test.go
- service/resource/vaultcrt/metric.go
See https://github.com/giantswarm/g8s-grafana/pull/21. Successfully tested on lycan.
> track version bundle versions in secret annotations

- helm/cert-operator-chart/templates/deployment.yaml
See https://github.com/giantswarm/aws-operator/pull/510/files
> Setting revisionHistoryLimit: 3

- examples/cert-operator-lab-chart/templates/deployment.yaml
This will prevent crash loops on lab operator start.
> fix local lab

- examples/cert-operator-lab-chart/templates/vault.yaml
For testing setting the Organization when issuing certs for RBAC.
> Update vault local chart to 0.7.3

- glide.lock
- service/resource/vaultcrt/desired_test.go
- vendor/github.com/giantswarm/certificatetpr/glide.lock
- vendor/github.com/giantswarm/certificatetpr/glide.yaml
- vendor/github.com/giantswarm/certificatetpr/spec.go
- vendor/github.com/giantswarm/certificatetpr/spec/version_bundle.go
- vendor/github.com/giantswarm/certificatetpr/spec_test.go
- vendor/github.com/giantswarm/certificatetpr/testdata/spec.yaml
- vendor/github.com/giantswarm/certificatetpr/tls_assets.go
- vendor/github.com/giantswarm/microerror/LICENSE
- vendor/github.com/giantswarm/microerror/README.md
- vendor/github.com/giantswarm/vaulthealthz/vaulthealthz.go
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
- vendor/github.com/prometheus/common/model/time.go
- vendor/github.com/prometheus/common/model/time_test.go
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/cobra/command_test.go
Fixes giantswarm/giantswarm#1857
> vendor: updated vaulthealthz

- service/framework.go
- service/service.go
This is basically just moving code to be able to more easily create another framework for the CRD watching later on.
> bundled framework creation in separate function

- service/keyv2/error.go
- service/keyv2/key.go
- service/keyv2/key_test.go
- service/resource/vaultcrtv2/create.go
- service/resource/vaultcrtv2/create_test.go
- service/resource/vaultcrtv2/current.go
- service/resource/vaultcrtv2/delete.go
- service/resource/vaultcrtv2/delete_test.go
- service/resource/vaultcrtv2/desired.go
- service/resource/vaultcrtv2/desired_test.go
- service/resource/vaultcrtv2/error.go
- service/resource/vaultcrtv2/metric.go
- service/resource/vaultcrtv2/resource.go
- service/resource/vaultcrtv2/update.go
- service/resource/vaultcrtv2/update_test.go
- service/resource/vaultpkiv2/create.go
- service/resource/vaultpkiv2/create_test.go
- service/resource/vaultpkiv2/current.go
- service/resource/vaultpkiv2/delete.go
- service/resource/vaultpkiv2/delete_test.go
- service/resource/vaultpkiv2/desired.go
- service/resource/vaultpkiv2/desired_test.go
- service/resource/vaultpkiv2/error.go
- service/resource/vaultpkiv2/resource.go
- service/resource/vaultpkiv2/spec.go
- service/resource/vaultpkiv2/update.go
See https://github.com/giantswarm/ingress-operator/pull/57.
> migrated v2 resources to using apiextensions types

- glide.lock
- vendor/github.com/beorn7/perks/quantile/stream.go
- vendor/github.com/beorn7/perks/quantile/stream_test.go
- vendor/github.com/giantswarm/apiextensions/pkg/apis/cluster/v1alpha1/aws_types.go
- vendor/github.com/giantswarm/apiextensions/pkg/apis/cluster/v1alpha1/azure_types.go
- vendor/github.com/giantswarm/apiextensions/pkg/apis/cluster/v1alpha1/common_types.go
- vendor/github.com/giantswarm/apiextensions/pkg/apis/cluster/v1alpha1/kvm_types.go
- vendor/github.com/giantswarm/vaulthealthz/error.go
- vendor/github.com/giantswarm/vaulthealthz/glide.lock
- vendor/github.com/giantswarm/vaulthealthz/metric.go
- vendor/github.com/giantswarm/vaulthealthz/vaulthealthz.go
- vendor/github.com/hashicorp/go-multierror/.travis.yml
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/api_test.go
- vendor/github.com/spf13/cobra/README.md
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/cobra/command_test.go
- vendor/github.com/spf13/cobra/doc/md_docs.go
Towards https://github.com/giantswarm/giantswarm/issues/2208.
> updated vendor deps

- .circleci/config.yml
- glide.lock
- glide.yaml
- integration/client.go
- integration/operator_test.go
- vendor/github.com/giantswarm/apiextensions/Gopkg.lock
- vendor/github.com/giantswarm/apiextensions/Gopkg.toml
- vendor/github.com/giantswarm/apiextensions/pkg/apis/core/v1alpha1/ingress_types.go
- vendor/github.com/giantswarm/apiextensions/pkg/apis/provider/v1alpha1/azure_types.go
- vendor/github.com/giantswarm/apiextensions/scripts/gen.sh
- vendor/github.com/giantswarm/certificatetpr/glide.lock
- vendor/github.com/giantswarm/certificatetpr/glide.yaml
- vendor/gopkg.in/yaml.v2/.travis.yml
- vendor/gopkg.in/yaml.v2/LICENSE
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/decode_test.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/example_embedded_test.go
- vendor/gopkg.in/yaml.v2/parserc.go
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
Uses an interface that unifies functionality from the common clientset and from our api extensions.
> use apiextensions in e2e test

- service/framework.go
- service/resource/vaultrolev1/create.go
- service/resource/vaultrolev1/current.go
- service/resource/vaultrolev1/delete.go
- service/resource/vaultrolev1/desired.go
- service/resource/vaultrolev1/error.go
- service/resource/vaultrolev1/resource.go
- service/resource/vaultrolev1/update.go
Towards https://github.com/giantswarm/giantswarm/issues/2362.
> added basic structure for vault role resource

- service/resource/vaultrolev1/current.go
- service/resource/vaultrolev1/desired.go
- service/resource/vaultrolev1/desired_test.go
- service/resource/vaultrolev1/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/2362.
> added basic implementation for GetDesiredState

- README.md
- service/framework.go
- service/resource/vaultcrtv2/create.go
- service/resource/vaultcrtv2/create_test.go
- service/resource/vaultcrtv2/delete_test.go
- service/resource/vaultcrtv2/desired_test.go
- service/resource/vaultcrtv2/resource.go
- service/resource/vaultcrtv2/update.go
- service/resource/vaultcrtv2/update_test.go
Towards https://github.com/giantswarm/giantswarm/issues/2362.
> enabled new role resource

- service/keyv2/key.go
- service/resource/vaultcrtv2/desired.go
- service/resource/vaultcrtv2/desired_test.go
- service/resource/vaultcrtv2/resource.go
- service/resource/vaultcrtv2/update.go
- service/resource/vaultcrtv2/update_test.go
Towards https://github.com/giantswarm/giantswarm/issues/2362.
> use config hash to detect updates

- main.go
- service/certconfig/v2/version_bundle.go
- service/version_bundles.go
Same as https://github.com/giantswarm/kvm-operator/pull/407, but for cert-operator.
> moved version bundle definitions to versioned folders

- Gopkg.lock
- vendor/github.com/giantswarm/vaulthealthz/vaulthealthz.go
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/sorter.go
- vendor/gopkg.in/yaml.v2/yaml.go
Follow up of https://github.com/giantswarm/vaulthealthz/pull/7
Towards https://github.com/giantswarm/vaultlab/pull/1
> vendor: update github.com/giantswarm/vaulthealthz

- helm/cert-operator-chart/templates/rbac.yaml
Towards https://github.com/giantswarm/k8scloudconfig/issues/290
> Update rbac doc version to v1

- Gopkg.lock
- service/controller/cert.go
- vendor/github.com/giantswarm/operatorkit/controller/controller.go
- vendor/github.com/giantswarm/operatorkit/controller/finalizer.go
- vendor/github.com/giantswarm/operatorkit/controller/resource_set.go
- vendor/github.com/giantswarm/operatorkit/informer/collector.go
- vendor/github.com/giantswarm/operatorkit/informer/error.go
- vendor/github.com/giantswarm/operatorkit/informer/informer.go
- vendor/github.com/giantswarm/operatorkit/informer/spec.go
Towards https://github.com/giantswarm/giantswarm/issues/3078
> Vendor update latest operatorkit

- helm/cert-operator-chart/templates/rbac.yaml
This is temporary and will be removed again here: https://github.com/giantswarm/giantswarm/issues/2148#issuecomment-384949696
> Add listing pods to RBAC role

- helm/cert-operator-chart/templates/deployment.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/3395
> Use release time to force pod redeploys

- Gopkg.lock
- service/controller/v2/key/key.go
- service/controller/v2/resources/vaultcrt/desired.go
- service/controller/v2/resources/vaultcrt/desired_test.go
- vendor/github.com/giantswarm/certs/k8s.go
- vendor/github.com/giantswarm/certs/searcher.go
Towards https://github.com/giantswarm/giantswarm/issues/3835
> service, vendor: create secrets with fmt style labels

- helm/cert-operator-chart/templates/deployment.yaml
- helm/cert-operator-chart/templates/psp.yaml
- helm/cert-operator-chart/values.yaml
Towards giantswarm/giantswarm/issues/6013
> run as non-root user

- service/controller/v2/resources/vaultcrt/current.go
Following https://github.com/giantswarm/cert-operator/pull/219
This would fix; https://github.com/giantswarm/cert-operator/pull/219#issuecomment-516467991
> Fix logging on cert types

- .circleci/config.yml
- helm/cert-operator-chart/templates/deployment.yaml
towards giantswarm/giantswarm#7435
push and use china image in china region
> push-and-use-china-registry

- helm/cert-operator-chart/templates/deployment.yaml
- helm/cert-operator-chart/templates/pull-secret.yml
The image is public, we don't need this.
> Remove image pull secret

- .gitignore
- helm/cert-operator/Chart.yaml
- helm/cert-operator/templates/configmap.yaml
- helm/cert-operator/templates/deployment.yaml
- helm/cert-operator/templates/psp.yaml
- helm/cert-operator/templates/rbac.yaml
- helm/cert-operator/templates/secret.yml
- helm/cert-operator/templates/service-account.yaml
- helm/cert-operator/templates/service.yaml
- helm/cert-operator/values.yaml
Towards giantswarm/giantswarm#9337 as part of giantswarm/giantswarm#7897.
Prelude to #261 to keep git history nice and clean.
> helm: copy chart to prepare flattened operator

- helm/cert-operator/Chart.yaml
- helm/cert-operator/templates/_helpers.tpl
- helm/cert-operator/templates/_resource.tpl
- helm/cert-operator/templates/configmap.yaml
- helm/cert-operator/templates/deployment.yaml
- helm/cert-operator/templates/psp.yaml
- helm/cert-operator/templates/rbac.yaml
- helm/cert-operator/templates/secret.yaml
- helm/cert-operator/templates/service-account.yaml
- helm/cert-operator/templates/service.yaml
- helm/cert-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/9337 as part of https://github.com/giantswarm/giantswarm/issues/7897.
> helm: update chart for flattening

- .circleci/config.yml
- CHANGELOG.md
- helm/cert-operator/Chart.yaml
- helm/cert-operator/ci/default-values.yaml
- helm/cert-operator/templates/psp.yaml
- helm/cert-operator/values.yaml
- main.go
- service/collector/set.go
- service/controller/cert.go
- service/controller/v2/key/key.go
- service/controller/v2/resources/vaultaccess/error.go
- service/controller/v2/resources/vaultcrt/create_test.go
- service/service.go
- service/version_bundles.go
Towards https://github.com/giantswarm/giantswarm/issues/9339
> circleci: use architect-orb to release cert-operator

- helm/cert-operator/templates/deployment.yaml
- helm/cert-operator/values.yaml
Fixes unique app deployment
Merge before #266
> helm: fix image tag

- service/controller/resources/vaultaccess/resource.go
- service/controller/resources/vaultcrt/resource.go
- service/controller/resources/vaultpki/resource.go
- service/controller/resources/vaultrole/resource.go
Towards: https://github.com/giantswarm/giantswarm/issues/9341
> flatten: rename resources

- pkg/project/project.go
Towards: https://github.com/giantswarm/giantswarm/issues/10389
> bump version to 0.1.0-dev

- CHANGELOG.md
- service/controller/cert.go
towards https://github.com/giantswarm/giantswarm/issues/10721
> Do not ensure CertConfig CRD

- .dependabot/config.yml
- .github/workflows/tidy.yml
- pkg/project/project.go
Adding all the dependabot magic & bumping the version.
> Add dependabot cleaning

- .circleci/config.yml
> Update architect orb to 0.10.0

- .circleci/config.yml
> No longer push to azure app collection

- .circleci/config.yml
> Do not automatically push to kvm-app-collection

- .circleci/config.yml
> Do not automatically push to aws-app-collection

- helm/cert-operator/templates/deployment.yaml
> Fix vault token flag

- .github/workflows/zz_generated.create_release.yaml
- .github/workflows/zz_generated.create_release_pr.yaml
- CHANGELOG.md
> Add github workflows

- CHANGELOG.md
- go.mod
- go.sum
- pkg/project/project.go
- service/controller/resources/vaultcrt/desired_test.go
Current `v0.3.10` breaks compatibility with already existing kvmconfigs
> Update apiextensios to v0.4.1

- CHANGELOG.md
- service/collector/vault.go
Towards https://github.com/giantswarm/giantswarm/issues/12157
> Report vault token expiration time as 0 when lookup fails

- .github/workflows/zz_generated.create_release_pr.yaml
- CHANGELOG.md
> Use architect 2.1.2 in github actions

- .github/workflows/zz_generated.create_release.yaml
- CHANGELOG.md
My release action here failed https://github.com/giantswarm/cert-operator/actions/runs/203867180
Validation is correct for this case, also we skip setting a new version as we need to keep the same version
> Skip non ref version

- .github/workflows/zz_generated.create_release.yaml
> Fix reference version output

- CHANGELOG.md
> Fix changelog after multiple failed releases

- .circleci/config.yml
> Update circleci orb

- CHANGELOG.md
- helm/cert-operator/templates/np.yaml
Towards https://github.com/giantswarm/giantswarm/issues/13207
> Add network policy resource

- README.md
> Remove Giantnetes from readme

- helm/cert-operator/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/14846
> Add team annotation to Chart.yaml

- .circleci/config.yml
- go.mod
- go.sum
> Bump protobuf to fix CVE

- README.md
Fixes https://github.com/giantswarm/giantswarm/issues/12903
> Add more docs about cert-operator behavior

- CHANGELOG.md
- helm/cert-operator/templates/configmap.yaml
- helm/cert-operator/values.yaml
some customers need different expiration threshold
> make-renew-expiration-configurable

- .circleci/config.yml
Towards: https://github.com/giantswarm/giantswarm/issues/24669
needed to run as unique app on azure and aws mcs
> push to azure and aws app collection

- .nancy-ignore
- CHANGELOG.md
- helm/cert-operator/templates/deployment.yaml
- helm/cert-operator/templates/pss-exceptions.yaml
- helm/cert-operator/values.schema.json
- helm/cert-operator/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2493
> add required values and exceptions for pss policies

- .nancy-ignore
- CHANGELOG.md
- helm/cert-operator/templates/pss-exceptions.yaml
> fix rule names of policy exception

- .nancy-ignore
- CHANGELOG.md
- helm/cert-operator/templates/psp.yaml
- helm/cert-operator/values.schema.json
- helm/cert-operator/values.yaml
> add toggle value for PSS migration

- CHANGELOG.md
- helm/cert-operator/templates/_helpers.tpl
towards https://github.com/giantswarm/giantswarm/issues/28871
> Add team label on resources

- helm/cert-operator/templates/_helpers.tpl
Towards
- https://github.com/giantswarm/giantswarm/issues/30245
> Fix app labels
